name: Terraform GCP CI/CD

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main

env:
  TF_VERSION: 1.6.6
  GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
  region: ${{ secrets.REGION }}
  zone: ${{ secrets.ZONE }}
  machine_type: ${{ secrets.MACHINE_TYPE }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        # working-directory: terraform
        run: terraform init

      - name: Select Terraform Workspace
        # working-directory: terraform
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            terraform workspace select prod || terraform workspace new prod
            cat <<EOF > prod.tfvars
            project_id=${{ secrets.PROJECT_ID }}
            region=${{ secrets.REGION }}
            zone=${{ secrets.ZONE }}
            machine_type=${{ secrets.MACHINE_TYPE }}
            EOF
          else
            terraform workspace select dev || terraform workspace new dev
            cat <<EOF > dev.tfvars
            project_id=${{ secrets.PROJECT_ID }}
            region=${{ secrets.REGION }}
            zone=${{ secrets.ZONE }}
            machine_type=${{ secrets.MACHINE_TYPE }}
            EOF
          fi

      - name: Terraform Format
        # working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Validate
        # working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        # working-directory: terraform
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            terraform plan --var-file prod.tfvars
          else
            terraform plan --var-file dev.tfvars
          fie

      - name: Terraform Apply
        # working-directory: terraform
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            terraform apply --var-file prod.tfvars --auto-approve
          else
            terraform apply --var-file dev.tfvars --auto-approve
          fie
