name: Terraform GCP CI/CD

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main

env:
  TF_VERSION: 1.6.6
  GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
  region: ${{ secrets.REGION }}
  zone: ${{ secrets.ZONE }}
  machine_type: ${{ secrets.MACHINE_TYPE }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        # working-directory: terraform
        run: terraform init

      - name: Select Terraform Workspace
        # working-directory: terraform
        run: |
          set -e
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "main" ]; then
            terraform workspace select prod || terraform workspace new prod
          else
            terraform workspace select dev || terraform workspace new dev
          fi

      # - name: Terraform Format
      #   # working-directory: terraform
      #   run: terraform fmt -check

      - name: Terraform Validate
        # working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        # working-directory: terraform
        run: |
          set -e
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "main" ]; then
            terraform plan \
              -var="project_id=${{ secrets.PROJECT_ID }}" \
              -var="region=${{ secrets.REGION }}" \
              -var="zone=${{ secrets.ZONE }}" \
              -var="machine_type=${{ secrets.MACHINE_TYPE }}"
          else
            terraform plan \
              -var="project_id=${{ secrets.PROJECT_ID }}" \
              -var="region=${{ secrets.REGION }}" \
              -var="zone=${{ secrets.ZONE }}" \
              -var="machine_type=${{ secrets.MACHINE_TYPE }}"
          fi

      - name: Terraform Apply
        # working-directory: terraform
        run: |
          set -e
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "main" ]; then
            terraform apply \
              -var="project_id=${{ secrets.PROJECT_ID }}" \
              -var="region=${{ secrets.REGION }}" \
              -var="zone=${{ secrets.ZONE }}" \
              -var="machine_type=${{ secrets.MACHINE_TYPE }}" \
              -auto-approve
          else
            terraform apply \
              -var="project_id=${{ secrets.PROJECT_ID }}" \
              -var="region=${{ secrets.REGION }}" \
              -var="zone=${{ secrets.ZONE }}" \
              -var="machine_type=${{ secrets.MACHINE_TYPE }}" \
              -auto-approve
          fi
